# Generated by Django 5.1.4 on 2025-11-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=200)),
                ("class_name", models.CharField(max_length=200)),
                ("duration", models.IntegerField(help_text="Minutes needed")),
                ("deadline", models.DateTimeField()),
                ("importance", models.IntegerField(help_text="1 = Low, 5 = High")),
                ("difficulty", models.IntegerField(help_text="1 = Low, 5 = High")),
            ],
        ),
    ]
